---
platform: linux

inputs:
- name: "git_repo_core-infrastructure-terraform"

run:
  dir: git_repo_core-infrastructure-terraform
  path: sh
  args:
    - "-ec"
    - |
      ./scripts/ci_setup.sh
      RI_TERRAFORM_ACTION="${RI_TERRAFORM_ACTION:-plan}"
      cd providers/aws/${RI_PROVIDER_DIR} && terraform init && terraform ${RI_TERRAFORM_ACTION}